server:
  port: 8111
  tomcat:
    accept-count: 10000
    connection-timeout: 10000
    max-connections: 2000
    max-threads: 2000
management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'info,health,prometheus'
  health:
    consul:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: zl123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 50
      max-active: 200
      max-idle: 200
      min-idle: 10
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      idle-timeout: 120000
      connection-timeout: 6000
      maxIdleTime: 60
  application:
    name: yh-scaffold-springboot-parent
  main:
      allow-bean-definition-overriding: true
  cloud:
    consul:
      config:
        data-key: configuration
        enabled: false
        format: yaml
        profile-separator: ','
        watch:
            wait-time: 5
      discovery:
          catalog-services-watch-delay: 30000
          health-check-critical-timeout: 30s
          instance-id: m-${spring.cloud.client.hostname}-${spring.application.name}-${spring.cloud.consul.host}-${spring.cloud.consul.port}
          prefer-ip-address: true
          register: true
          service-name: app-${spring.application.name}-${spring.profiles.active}
      enabled: true
      host: localhost
      port: 8500
      retry:
          retryInterval: 60000
          enable: true
    discovery:
      client:
         composite-indicator:
           enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        pool:
          maxIdleTime: 10000
  profiles:
    active: local
  project:
    name: yh-app-templat
apollo:
  bootstrap:
    eagerLoad:
      enabled: false
    enabled: false
    namespaces: application.yml
  cacheDir: /opt/data/apollo-cache
  cluster: SH
  meta: http://apollo-dev-sh.yonghui.cn:8080
app:
  id: yh-app-templat--yh-scaffold-springboot-parent


