spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db??useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: appAdmin
    password: Abc123..
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 50
      max-active: 200
      max-idle: 200
      min-idle: 10
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      idle-timeout: 120000
      connection-timeout: 6000
      maxIdleTime: 60