spring:
  application:
    name: yh-scaffold-springboot-parent
    main:
     allow-bean-definition-overriding: true
  cloud:
    #    gateway:
    #      routes:
    #        - id: testGGGG
    #          uri: app-abc-test111
    #          predicates:
    #            - Path=/abc-test111/**
    #        - id: ROSS-activity
    #          uri: lb://app-yonghui-ross-activity
    #          predicates:
    #            - Path=/activity/**
    #    gateway:
    #      routes:
    #        - id: yh-demo-test-svc
    #          uri: http://localhost:8101
    #          predicates:
    #            - Path=/show-test/**
    consul:
      config:
        discovery:
          catalog-services-watch-delay: 30000
          health-check-critical-timeout: 30s
          instance-id: m-${spring.cloud.client.hostname}-${spring.application.name}-${spring.cloud.consul.host}-${spring.cloud.consul.port}
          prefer-ip-address: true
          register: true
          service-name: app-${spring.application.name}-${spring.profiles.active}
        enabled: true
        host: localhost
        port: 8500
        retry:
          retryInterval: 60000
          enable: true
  profiles:
    active: local
  project:
    name: yh-app-templat
apollo:
  bootstrap:
    eagerLoad:
      enabled: false
    enabled: false
    namespaces: application.yml
  cacheDir: /opt/data/apollo-cache
  cluster: SH
  meta: http://apollo-dev-sh.yonghui.cn:8080
app:
  id: yh-app-templat--yh-scaffold-springboot-parent
mybatis:
  config-location: "classpath:mybatis-config.xml"
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8111
  tomcat:
    accept-count: 10000
    connection-timeout: 10000
    max-connections: 2000
    max-threads: 2000