spring:
  application:
    name: yh-scaffold-springboot-parent
  project:
    name: yh-app-templat
apollo:
  bootstrap:
    eagerLoad:
      enabled: false
    enabled: false
    namespaces: application.yml
  cacheDir: /opt/data/apollo-cache
  cluster: SH
  meta: http://apollo-dev-sh.yonghui.cn:8080
app:
  id: yh-app-templat--yh-scaffold-springboot-parent
mybatis:
  mapper-locations: classpath:mapper/*.xml